/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MobileWalletRouteImport } from './routes/mobile-wallet'
import { Route as IndexRouteImport } from './routes/index'

const MobileWalletRoute = MobileWalletRouteImport.update({
  id: '/mobile-wallet',
  path: '/mobile-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile-wallet': typeof MobileWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile-wallet': typeof MobileWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mobile-wallet': typeof MobileWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mobile-wallet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mobile-wallet'
  id: '__root__' | '/' | '/mobile-wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MobileWalletRoute: typeof MobileWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mobile-wallet': {
      id: '/mobile-wallet'
      path: '/mobile-wallet'
      fullPath: '/mobile-wallet'
      preLoaderRoute: typeof MobileWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MobileWalletRoute: MobileWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
